### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by yanjiez** [thompsonsj/slate-serializers#146]
```

WARNING in ./node_modules/@slate-serializers/dom/src/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/index.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/config/default.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/config/default.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/config/default.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/config/payload.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/config/payload.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/config/payload.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/config/slateDemo.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/config/slateDemo.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/config/slateDemo.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/dom.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/dom.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/dom.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/serializers.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/serializers.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/serializers.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/utilities/convert-slate.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/utilities/convert-slate.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/utilities/convert-slate.ts'

WARNING in ./node_modules/@slate-serializers/dom/src/lib/utilities/domhandler.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/dom/src/lib/utilities/domhandler.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/dom/src/lib/utilities/domhandler.ts'

WARNING in ./node_modules/@slate-serializers/html/src/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/index.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/html.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/html.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/html.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/htmlToSlate/config/default.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/default.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/default.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/htmlToSlate/config/payload.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/payload.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/payload.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/htmlToSlate/config/slateDemo.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/slateDemo.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/config/slateDemo.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/htmlToSlate/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/index.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/htmlToSlate/whitespace.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/whitespace.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/htmlToSlate/whitespace.ts'

WARNING in ./node_modules/@slate-serializers/html/src/lib/serializers/slateToHtml/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/html/src/lib/serializers/slateToHtml/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/html/src/lib/serializers/slateToHtml/index.ts'

WARNING in ./node_modules/@slate-serializers/utilities/src/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/utilities/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/utilities/src/index.ts'

WARNING in ./node_modules/@slate-serializers/utilities/src/lib/blocks.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/utilities/src/lib/blocks.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/utilities/src/lib/blocks.ts'

WARNING in ./node_modules/@slate-serializers/utilities/src/lib/style-object.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/utilities/src/lib/style-object.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/utilities/src/lib/style-object.ts'

WARNING in ./node_modules/@slate-serializers/utilities/src/lib/utilities.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/{projectPath}/packages/utilities/src/lib/utilities.ts' file: Error: ENOENT: no such file or directory, open '/Users/{projectPath}/packages/utilities/src/lib/utilities.ts'

```

**Comment by polyakov84** [comment]
I faced the same errors

**Comment by thompsonsj** [comment]
I have no idea where to start - haven't been able to reproduce this.

I am hoping that this is resolved in https://github.com/thompsonsj/slate-serializers/releases/tag/v2.2.0 where a lot of dependencies have been updated. If not, any more information to help me recreate this? e.g. node version?

**Comment by polyakov84** [comment]
I checked the new 2.2.0 version and the issue is still present.

Node version 16.10.0

Please let me know what additional information I could provide to help to find and resolve the issue.

**Comment by shank-eric** [comment]
I believe this is related to what files are actually being included in the package, which does include the sourcemap files, but not the ts files that the sourcemaps are trying to point to.  For example, when I look at the `@slate-serializers/dom/src/index.js.map` [on npm](https://www.npmjs.com/package/@slate-serializers/dom?activeTab=code) it's trying to include this file as a source: `"../../../../packages/dom/src/index.ts"`.  But no index.ts is present in the src folder in the package, so it's unable to find the file.  Also, even if the index.ts file was present, I'm not sure that this source path would resolve correctly as the ../../../../packages doesn't seem like it corresponds well to where the file would be once it's in a node_modules.

On the other hand, if you adjust your source-map-loader configuration, you can tell it to ignore these files and make the warnings go away.  Something like:
```
loader.exclude = [path.resolve(__dirname, '../../libs/reactifi/node_modules/@slate-serializers')];
```

**Comment by thompsonsj** [comment]
Thanks @shank-eric and @yanjiez . Version 2.2.1 no longer includes source maps, so those warnings should go away 👍  I'll bring back source maps if I can figure out how to generate them properly in a monorepo or [NX adds guidance/support for this](https://github.com/nrwl/nx/issues/11179).

**Comment by mg-code** [comment]
@thompsonsj since 2.2.3 sourcemaps are re-enabled, but errors are still present.
